server:
  port: 8083

spring:
  activemq:
    broker-url: tcp://192.168.86.128:61616
    user: admin
    password: admin

  jms:
    pub-sub-domain: true  #topic订阅

myTopicName: springboot-activemq-topic